### ISSUE TITLE
Set up dashboard using Open SDG Quick Start guide

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/OIF-Dashboard-Site#1]
- [x] Change the logo
- [x] Change the favicon
- [x] Configure the frontpage
- [x] Add indicators
- [x] Change the colours
- [x] Change the site-wide banner
